// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package models

import "database/sql"

func ScanUser(r *sql.Row) (User, error) {
	var s User
	if err := r.Scan(
		&s.Id,
		&s.Name,
		&s.IsParent,
	); err != nil {
		return User{}, err
	}
	return s, nil
}

func ScanUsers(rs *sql.Rows) ([]User, error) {
	structs := make([]User, 0, 16)
	var err error
	for rs.Next() {
		var s User
		if err = rs.Scan(
			&s.Id,
			&s.Name,
			&s.IsParent,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func ScanFlaggedText(r *sql.Row) (FlaggedText, error) {
	var s FlaggedText
	if err := r.Scan(
		&s.Id,
		&s.Content,
		&s.Confidence,
		&s.Sent,
		&s.UserId,
	); err != nil {
		return FlaggedText{}, err
	}
	return s, nil
}

func ScanFlaggedTexts(rs *sql.Rows) ([]FlaggedText, error) {
	structs := make([]FlaggedText, 0, 16)
	var err error
	for rs.Next() {
		var s FlaggedText
		if err = rs.Scan(
			&s.Id,
			&s.Content,
			&s.Confidence,
			&s.Sent,
			&s.UserId,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

