version: 3.1
services:
  db:
    build: db/.
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: bully
  rabbitmq:
      image: rabbitmq
      ports:
        - 5672