version: '3.1'
services:
  db:
    build: db/.
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: bully
  rabbitmq:
      image: rabbitmq
      ports:
        - "5672:5672"
  api:
    build:
      context: "src/bitcamp"
      dockerfile: "api.dockerfile"
    ports:
      - "8080:8080"
    restart: always
    environment:
      DOCKER: 'true'
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: bully

    depends_on:
      - rabbitmq
      - db
  worker:
    build:
      context: "src/bitcamp"
      dockerfile: "worker.dockerfile"
    restart: always
    environment:
      DOCKER: 'true'
    depends_on:
      - rabbitmq
      - db